# GitHub Activity Check Configuration

# Output format: "default" or "json"
format = "json"

# Minimum number of commits for established project
min_commits = 150

# Minimum number of contributors for established project  
min_contributors = 5

# Maximum days since last commit for active project
max_days = 30

# Scale for open pull requests scoring
prs_scale = 15.0

# Scale for open issues scoring
issues_scale = 25.0